ddcCajamarca.Web/Controllers/AgendaCulturalController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Syncfusion.XlsIO;
using System.Web.Mvc;
using ddcCajamarca.Services.ActividadesCulturales.Interfaces;
using ddcCajamarca.Services.Seguridad.Interfaces;
using ddcCajamarca.Models;
using System.Globalization;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Parsing;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using System.Drawing;
using System.Web.Security;

namespace ddcCajamarca.Web.Controllers
{
    public class AgendaCulturalController : Controller
    {
        public IAmbienteService ambienteService { get; set; }
        public IActivoService activoService { get; set; }
        public IEventoEnsayoService eventoEnsayoService { get; set; }
        public IPerfilUsuarioService perfilUsuarioService { get; set; }
        public IRegUsuarioService regUsuarioService { get; set; }

        public AgendaCulturalController(IAmbienteService ambienteService, IActivoService activoService, IEventoEnsayoService eventoEnsayoService,
            IPerfilUsuarioService perfilUsuarioService, IRegUsuarioService regUsuarioService)
        {
            this.ambienteService = ambienteService;
            this.activoService = activoService;     
            this.eventoEnsayoService = eventoEnsayoService;
            this.perfilUsuarioService = perfilUsuarioService;
            this.regUsuarioService = regUsuarioService;
        }

        [HttpGet]
        public ActionResult ValidadFechaNuevo(Int32 idAmbientes, String FechaIni, String FechaFin, Boolean opcTodoDia, String HoraIni, String HoraFin,
            Boolean cbLunes, Boolean cbMartes, Boolean cbMiercoles, Boolean cbJueves, Boolean cbViernes, Boolean cbSabado, Boolean cbDomingo)
        {
            try
            {
                var horin = TimeSpan.Parse(HoraIni);
                var horfin = TimeSpan.Parse(HoraFin);

                if (horfin < horin)
                {
                    ViewBag.MSG = "HI";

                    return PartialView("_Mensaje");
                }

                if (cbLunes || cbMartes || cbMiercoles || cbJueves || cbViernes || cbSabado || cbDomingo)
                {
                    var eventos = eventoEnsayoService.ObtenerDetalleHorasEventoPorFecha(DateTime.Parse(FechaIni), DateTime.Parse(FechaFin + " 23:59"), "");

                    DateTime FechaIniFind;
                    DateTime FechaFinFind;

                    if (opcTodoDia)
                    {
                        FechaIniFind = DateTime.Parse(FechaIni);
                        FechaFinFind = DateTime.Parse(FechaIni);
                    }
                    else
                    {
                        FechaIniFind = DateTime.Parse(FechaIni + " " + HoraIni);
                        FechaFinFind = DateTime.Parse(FechaFin + " " + HoraFin);
                    }

                    var encontrado = false;

                    foreach (var item in eventos)
                    {
                        if (item.EventoEnsayo.IdAmbiente == idAmbientes)
                        {
                            if (item.EventoEnsayo.TodoDia)
                            {
                                encontrado = true;
                                break;
                            }
                            else
                            {
                                if (item.FechaInicio.Hour <= FechaFinFind.Hour && item.FechaFin.Hour >= FechaIniFind.Hour)
                                {
                                    if (item.FechaInicio.Hour == FechaFinFind.Hour)
                                    {
                                        if (item.FechaInicio.Minute < FechaFinFind.Minute)
                                        {
                                            if (cbLunes)
                                            {
                                                if (item.EventoEnsayo.Lunes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbMartes)
                                            {
                                                if (item.EventoEnsayo.Martes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbMiercoles)
                                            {
                                                if (item.EventoEnsayo.Miercoles)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbJueves)
                                            {
                                                if (item.EventoEnsayo.Jueves)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbViernes)
                                            {
                                                if (item.EventoEnsayo.Viernes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbSabado)
                                            {
                                                if (item.EventoEnsayo.Sabado)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbDomingo)
                                            {
                                                if (item.EventoEnsayo.Domingo)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                        }
                                    }
                                    else if (item.FechaFin.Hour == FechaIniFind.Hour)
                                    {
                                        if (item.FechaFin.Minute > FechaIniFind.Minute + 1)
                                        {
                                            if (cbLunes)
                                            {
                                                if (item.EventoEnsayo.Lunes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbMartes)
                                            {
                                                if (item.EventoEnsayo.Martes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbMiercoles)
                                            {
                                                if (item.EventoEnsayo.Miercoles)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbJueves)
                                            {
                                                if (item.EventoEnsayo.Jueves)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbViernes)
                                            {
                                                if (item.EventoEnsayo.Viernes)
                                                {
                                                    encontrado = true;
                                                    break;
                                                }
                                            }
                                            if (cbSabado)
                                            {
                                                if (item.EventoEnsayo.Sabado)
                                                {
                                                    encontrado = true;
                                                    break;

ddcCajamarca.Web/Views/AgendaCultural/ModificarRegistro.cshtml
@{
    ViewBag.Title = "Agenda Cultural";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Agenda Cultural</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Inicio</a>
            </li>
            <li>
                Agenda Cultural
            </li>
            <li class="active">
                <strong>Modificar Registro</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h2>
                    Formulario - Modificar Evento
                </h2>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <form action="@Url.Action("ModificarRegistro", "AgendaCultural")" enctype="multipart/form-data" method="post">
                        <div class="form-group col-lg-12">
                            <div class="col-lg-9 b-r">
                                <div class="form-group col-lg-6">
                                    <label>Sala</label>
                                    <input name="NombreAmbiente" readonly class="form-control" value="@Model.Ambiente.NombreMostrar" style="text-transform:uppercase;" required>
                                    <input name="IdAmbiente" hidden value="@Model.IdAmbiente">
                                    <input name="Id" hidden value="@Model.Id">
                                    <input name="opcTodoDia" hidden value="@ViewBag.opcTodoDia">
                                </div>

                                <div class="form-group col-lg-6">
                                    <label>Fecha de Registro</label>
                                    <input name="FechaRegistro" type="text" class="form-control" readonly value="@Model.FechaRegistroMDA" />
                                </div>

                                <div class="form-group col-lg-6">
                                    <label>Nombre de la Actividad - Agrupacion</label>
                                    <input name="NombreActividad" id="NombreActividad" value="@Model.NombreActividad" autocomplete="off" placeholder="INGRESE NOMBRE" class="form-control" style="text-transform:uppercase;" required>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Institución/Persona Encargada</label>
                                    <input name="InstitucionEncargada" id="InstitucionEncargada" autocomplete="off" value="@Model.InstitucionEncargada" placeholder="INGRESE NOMBRE" class="form-control" style="text-transform:uppercase;" required>
                                </div>

                                <div class="form-group col-lg-12" id="idrequerimiento">
                                    <div class="col-lg-12">
                                        <label>Requerimientos</label>
                                    </div>

                                    <div class="form-group col-lg-6">
                                        <p>Disponibles</p>
                                        <ul class="sortable-list connectList agile-list" id="todo">

                                            @{
                                                var x = 0;
                                                var band = false;
                                                foreach (var item in @ViewBag.Activos)
                                                {
                                                    foreach (var itemdet in Model.DetalleRequerimientos)
                                                    {
                                                        if (item.Id == itemdet.IdActivo)
                                                        {
                                                            band = true;
                                                            break;
                                                        }
                                                    }

                                                    if (!band)
                                                    {
                                                        <li class="success-element" id="@item.Id">
                                                            @item.Nombre
                                                            <input name="DetalleRequerimientos[@x].Cantidad" value="@item.Cantidad" class="pull-right numval" max="@item.Cantidad" type="number" min="1" style="width:50px; text-align:center;" />
                                                            <input name="DetalleRequerimientos[@x].IdActivo" hidden value="@item.Id" />
                                                            <input name="DetalleRequerimientos[@x].Id" hidden value="0" />
                                                        </li>
                                                        x++;
                                                    }

                                                    band = false;
                                                }

                                            }
                                        </ul>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <p>Agregados</p>
                                        <ul class="sortable-list connectList agile-list" id="enprogreso">
                                            @{

                                                foreach (var item in Model.DetalleRequerimientos)
                                                {
                                                    <li class="success-element" id="@item.IdActivo">
                                                        @item.Activo.Nombre
                                                        <input name="DetalleRequerimientos[@x].Cantidad" value="@item.Cantidad" class="pull-right numval" max="@item.Activo.Cantidad" type="number" min="1" style="width:50px; text-align:center;" />
                                                        <input name="DetalleRequerimientos[@x].IdActivo" hidden value="@item.Activo.Id" />
                                                        <input name="DetalleRequerimientos[@x].Id" hidden value="@item.Id" />
                                                    </li>
                                                    x++;
                                                }

                                            }
                                        </ul>
                                    </div>


                                </div>

                                <div class="form-group col-lg-12">
                                    <label>Información adicional</label>
                                    <textarea name="info" class="form-control" rows="5" style="text-transform:uppercase;">@Model.InformacionAdicional</textarea>
                                </div>
                            </div>
                            <div class="col-lg-3" id="paso2">
                                <div class="form-group col-lg-12">
                                    <label>Fecha Inicio</label>
                                    <div class="input-group">
                                        <input name="FechaInicio" type="text" readonly class="form-control" value="@Model.FechaInicioMostrar"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12">
                                    <label>Fecha Fin</label>
                                    <div class="input-group">
                                        <input name="FechaFin" type="text" readonly class="form-control" value="@Model.FechaFinMostrar"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12">
                                    <label>Hora Incio</label>
                                    <div class="input-group clockpicker" data-autoclose="true">
                                        <input type="text" class="form-control" name="HoraIni" readonly value="@Model.HoraInicioMostrar">
                                        <span class="input-group-addon">
                                            <span class="fa fa-clock-o"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group col-lg-12">
                                    <label>Hora Fin</label>
                                    <div class="input-group clockpicker" data-autoclose="true">
                                        <input type="text" class="form-control" name="HoraFin" readonly value="@Model.HoraFinMostrar">
                                        <span class="input-group-addon">
                                            <span class="fa fa-clock-o"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <input id="Eventotipo" name="Eventotipo" hidden value="@ViewBag.Evento" />


                            <div class="form-group col-lg-12">
                                <input hidden type="text" name="arryreq" id="arryreq" value="" />
                                <div class="text-right">
                                    <button class="btn btn-sm btn-success m-t-n-xs" type="submit"><strong>Guardar</strong></button>
                                </div>
                            </div>


                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    @*<div class="row">
            <div class="col-lg-12">
                <h4>
                    Serialised Output
                </h4>
                <p>
                    Serializes the sortable's item id's into an array of string.
                </p>
                <div class="output p-m m white-bg"></div>

            </div>
        </div>*@
</div>


@section Styles {

}
@section Scripts {
    @Scripts.Render("~/plugins/typehead")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/plugins/touchPunch")

    <script type="text/javascript">

        $(document).ready(function () {

            $("#todo, #enprogreso").sortable({
                connectWith: ".connectList",
                update: function (event, ui) {

                    var todo = $("#todo").sortable("toArray");
                    var inprogress = $("#enprogreso").sortable("toArray");
                    //$('.output').html("ToDo: " + window.JSON.stringify(todo) + "<br/>" + "In Progress: " + window.JSON.stringify(inprogress));
                    $('#arryreq').val(inprogress);
                }
            }).disableSelection();

            @*if ('@ViewBag.Evento' == 'True') {
                $('#Eventotipo').val('true');
                document.getElementById("idrequerimiento").hidden = false;
            } else {
                $('#Eventotipo').val('false');
                document.getElementById("idrequerimiento").hidden = true;
            }*@

        });
        //Comillas
        //$('#NombreActividad').keypress(function (tecla) {
        //    if (tecla.charCode == 34) return false;
        //});
        //$('#InstitucionEncargada').keypress(function (tecla) {
        //    if (tecla.charCode == 34) return false;
        //});
        $('.numval').keypress(function (key) {
            return false;
        });

    </script>
}

ddcCajamarca.Web/Views/AgendaCultural/_BuscarActivo.cshtml
<div class="col-sm-12 text-right">
    <p>@ViewBag.Coincidencias resultados encontrados.</p>
</div>
<table class="table table-stripped" data-show-toggle="false" data-filtering="true" data-page-size="10">
    <thead>

        <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>FechaRegistro</th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>
    <tbody>

        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.Cantidad</td>
                    <td>@item.FechaRegistroMostrar</td>
                    <td class="text-center">
                        <div class="btn-group">
                            <a href="#" class="btn btn-warning btn-xs" onclick="abrirmodalmod(@item.Id)">Modificar</a>
                            <a href="#" class="btn btn-danger btn-xs" onclick="abrirmodalelim(@item.Id)">Eliminar</a>
                        </div>
                    </td>
                </tr>
            }
        }

    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

ddcCajamarca.Web/Views/AgendaCultural/_BuscarAmbiente.cshtml
<div class="col-sm-12 text-right">
    <p>@ViewBag.Coincidencias resultados encontrados.</p>
</div>
<table class="table table-stripped" data-show-toggle="false" data-filtering="true" data-page-size="10">
    <thead>

        <tr>
            <th>Nombre</th>
            <th>Aforo</th>
            <th>Color</th>
            <th>FechaRegistro</th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>
    <tbody>

        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.Aforo</td>
                    <td style="color:@item.Color">@item.Color</td>
                    <td>@item.FechaRegistroMostrar</td>
                    <td class="text-center">
                        <div class="btn-group">
                            <a href="#" class="btn btn-warning btn-xs" onclick="abrirmodalmod(@item.Id)">Modificar</a>
                            <a href="#" class="btn btn-danger btn-xs" onclick="abrirmodalelim(@item.Id)">Eliminar</a>
                        </div>
                    </td>
                </tr>
            }
        }

    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

ddcCajamarca.Web/Views/AgendaCultural/_BuscarEventoReporte.cshtml
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Sala/Patio</th>
            @{
                for (int i = 0; i < ViewBag.contdias; i++)
                {
                    <th>@ViewBag.nombredias[i]</th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @{
            for (int i = 0; i < @ViewBag.salas; i++)
            {
                <tr class="gradeX">
                    <td>@ViewBag.detalle[i, 0]</td>
                    @for (int j = 0; j < @ViewBag.contdias; j++)
                    {
                        <td>@Html.Raw(HttpUtility.HtmlDecode(@ViewBag.detalle[i, j + 1]))</td>
                    }
                </tr>
            }
        }


    </tbody>
    <tfoot>
        <tr>
            <th>Sala/Patio</th>
            @{
                for (int i = 0; i < ViewBag.contdias; i++)
                {
                    <th>@ViewBag.nombredias[i]</th>
                }
            }
        </tr>
    </tfoot>
</table>

ddcCajamarca.Web/Views/AgendaCultural/_OBtenerActivoPorId.cshtml
<div class="form-group col-lg-12">
    <label>Fecha de Registro</label>
    <input name="FechaRegistro" type='text' class="form-control" readonly value="@ViewBag.FechaHoy" />
</div>
<div class="form-group col-lg-12">
    <label>Nombre*</label>
    <input name="txtNombre" id="txtNombreMod" value="@Model.Nombre" placeholder="INGRESE NOMBRE" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required>
</div>
<div class="form-group col-lg-12">
    <label>Cantidad</label>
    <input name="Cantidad" id="txtCantidadMod" value="@Model.Cantidad" placeholder="INGRESE AFORO" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required>
</div>
<br />
<p><div class="form-group">*El campo nombre es obligatorio</div> </p>
<input id="txtIdMod" hidden value="@Model.Id" />

ddcCajamarca.Web/Views/AgendaCultural/_OBtenerAmbientePorId.cshtml
<div class="form-group col-lg-12">
    <label>Fecha de Registro</label>
    <input name="FechaRegistro" type='text' class="form-control" readonly value="@ViewBag.FechaHoy" />
</div>
<div class="form-group col-lg-12">
    <label>Nombre*</label>
    <input name="txtNombreMod" id="txtNombreMod" value="@Model.Nombre" placeholder="INGRESE NOMBRE" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required>
</div>
<div class="form-group col-lg-12">
    <label>Aforo</label>
    <input name="txtAforoMod" id="txtAforoMod" value="@Model.Aforo" placeholder="INGRESE AFORO" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required>
</div>
<div class="form-group col-lg-12">
    <label>Color</label>
    <select class="form-control" id="idopcioncolorMod" name="idopcioncolorMod">
        <option style="color:white ;background-color:#2591F6">Azul</option>
        <option style="color:white ;background-color:#EAE54E">Amarillo</option>
        <option style="color:white ;background-color:#5D0560">Berenjena</option>
        <option style="color:white ;background-color:#66C4E5">Celeste</option>
        <option style="color:white ;background-color:#F5D4F4">Chicle</option>
        <option style="color:white ;background-color:#27F8F5">Cielo</option>
        <option style="color:white ;background-color:#A023A4">Ciruela</option>
        <option style="color:white ;background-color:#F31ADE">Fresa</option>
        <option style="color:white ;background-color:#F4DA18">Limon</option>
        <option style="color:white ;background-color:#8D7CCA">Orquidea</option>
        <option style="color:white ;background-color:#337352">Musgo</option>
        <option style="color:white ;background-color:#C352D4">Magenta</option>
        <option style="color:white ;background-color:#F00C82">Morado</option>
        <option style="color:white ;background-color:#E79742">Naranja</option>
        <option style="color:white ;background-color:#EE79E3">Rosa</option>
        <option style="color:white ;background-color:#FF0000">Rojo</option>
        <option style="color:white ;background-color:#8A0808">Rojo Oscuro</option>
        <option style="color:white ;background-color:#397402">Trebol</option>
        <option style="color:white ;background-color:#50B258">Verde</option>
    </select>
</div>
<br />
<p><div class="form-group">*El campo nombre es obligatorio</div> </p>
<input id="txtIdMod" hidden value="@Model.Id" />