ddcCajamarca.Web/Controllers/DirectorioController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ddcCajamarca.Services.Directorio.Interfaces;
using ddcCajamarca.Services.Seguridad.Interfaces;
using ddcCajamarca.Models;
using System.Drawing;
using Syncfusion.XlsIO;
using System.Web.Security;

namespace ddcCajamarca.Web.Controllers
{
    public class DirectorioController : Controller
    {
        public IPersonaService personaService { get; set; }
        public IOrganizacionService organizacionService { get; set; }
        public IProfesionService profesionService { get; set; }
        public IOcupacionCulturalService ocupacionCulturalService { get; set; }
        public IPerfilUsuarioService perfilUsuarioService { get; set; }
        public IRegUsuarioService regUsuarioService { get; set; }

        public DirectorioController(IPersonaService personaService, IOrganizacionService organizacionService,
            IProfesionService profesionService, IOcupacionCulturalService ocupacionCulturalService,
            IPerfilUsuarioService perfilUsuarioService, IRegUsuarioService regUsuarioService)
        {
            this.personaService = personaService;
            this.organizacionService = organizacionService;
            this.profesionService = profesionService;
            this.ocupacionCulturalService = ocupacionCulturalService;
            this.perfilUsuarioService = perfilUsuarioService;
            this.regUsuarioService = regUsuarioService;
        }
        
        [HttpGet]
        [Authorize(Roles = "SuperAdmin, Administrador, Promotor, Reportes")]
        public ActionResult ListarPersonas(String NA, String Fun)
        {
            var u = Membership.GetUser(User.Identity.Name);

            var usuario = perfilUsuarioService.ObtenerPerfilUsuarioPorNombre(User.Identity.Name);

            foreach (var item in usuario.webpages_UsersInRoles)
            {
                ViewBag.Rol = item.webpages_Roles.RoleName;
            }

            var result = personaService.ObtenerPersonaPorCriterio("");

            foreach (var item in result)
            {
                item.Imagen = ".." + item.Imagen;
            }

            if (!String.IsNullOrEmpty(Fun))
            {
                ViewBag.dato = NA;
                ViewBag.save = Fun;
            }
            else
            {
                ViewBag.dato = "";
                ViewBag.save = false;
            }
            ViewBag.Coincidencias = result.Count();
            ViewBag.Organizacion = organizacionService.ObtenerOrganizacionPorCriterio("",false);
            ViewBag.Ocupacion = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", false);
            ViewBag.Profesion = profesionService.ObtenerProfesionPorCriterio("", false);

            return View(result);
        }
        
        [HttpGet]
        [Authorize(Roles = "SuperAdmin, Administrador, Promotor, Reportes")]
        public ActionResult ListarPersonas2(String NA, String Fun)
        {
            var result = personaService.ObtenerPersonaPorCriterio("");

            foreach (var item in result)
            {
                item.Imagen = ".." + item.Imagen;
            }

            if (!String.IsNullOrEmpty(Fun))
            {
                ViewBag.dato = NA;
                ViewBag.save = Fun;
            }
            else
            {
                ViewBag.dato = "";
                ViewBag.save = false;
            }
            ViewBag.Organizacion = organizacionService.ObtenerOrganizacionPorCriterio("", true);
            ViewBag.Ocupacion = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", true);
            ViewBag.Profesion = profesionService.ObtenerProfesionPorCriterio("", true);

            return View(result);
        }
        
        [HttpGet]
        [Authorize(Roles = "SuperAdmin, Administrador")]
        public ActionResult ListarExtras(String Tp)
        {
            ViewBag.FechaHoy = FechaHoy();

            if (!String.IsNullOrEmpty(Tp))
            {
                ViewBag.ToasMS = Tp;
            }
            else
            {
                ViewBag.ToasMS = "";
            }
            

            if (Tp == "G1")
            {
                ViewBag.msgini = "G1";

                var result = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else if (Tp == "G2")
            {
                ViewBag.msgini = "G2";

                var result = profesionService.ObtenerProfesionPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else if (Tp == "G3")
            {
                ViewBag.msgini = "G3";

                var result = organizacionService.ObtenerOrganizacionPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else if (Tp == "M1")
            {
                ViewBag.msgini = "M1";

                var result = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else if (Tp == "M2")
            {
                ViewBag.msgini = "M2";

                var result = profesionService.ObtenerProfesionPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else if (Tp == "M3")
            {
                ViewBag.msgini = "M3";

                var result = organizacionService.ObtenerOrganizacionPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            else
            {
                ViewBag.msgini = "G4";

                var result = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", false);
                ViewBag.Coincidencias = result.Count();

                ViewBag.Ocupacion = result;
            }
            
            return View();
        }
        
        [HttpGet]
        [Authorize(Roles = "SuperAdmin, Administrador, Promotor")]
        public ActionResult NuevaPersona()
        {
            ViewBag.Organizacion = organizacionService.ObtenerOrganizacionPorCriterio("", false);
            ViewBag.Ocupacion = ocupacionCulturalService.ObtenerOcupacionCulturalPorCriterio("", false);
            ViewBag.Profesion = profesionService.ObtenerProfesionPorCriterio("", false);
            ViewBag.FechaHoy = FechaHoy();
            
            ViewBag.Personas = DataPersonasAutocomplete();

            return View();
        }

        private string DataPersonasAutocomplete()
        {
            var personas = personaService.ObtenerPersonaPorCriterio("");

            var personasarray = "";

            foreach (var item in personas)
            {
                personasarray = personasarray + "'" + item.NombreMostrar + "'" + ",";
            }

            personasarray = "[" + personasarray + "'" + "'" + "]";

            personasarray = personasarray.Replace("'", char.ConvertFromUtf32(34));

            return personasarray;
        }
        
        [HttpPost]
        [Authorize(Roles = "SuperAdmin, Administrador, Promotor")]
        public ActionResult NuevaPersona(Persona model, HttpPostedFileBase file, String cropweight, String cropwidth, String cropx, String cropy)
        {
            try
            {
                if (file != null && file.ContentType.Remove(5) == "image")
                {
                    string ruta = Server.MapPath("~/PerfilImg");

                    if (!Directory.Exists(ruta))
                        Directory.CreateDirectory(ruta);

                    string archivo = String.Format("{0}\\{1}", ruta, model.Telefono + "-" + model.NombreApellidos + "." + file.ContentType.Remove(0, 6));
                    //string archivo = "C:/inetpub/wwwroot/DDCCajamarca/PerfilImg/" + model.Telefono + " -" + model.NombreApellidos;

                    cropweight = cropweight.Replace(".", ",");
                    cropwidth = cropwidth.Replace(".", ",");
                    cropx = cropx.Replace(".", ",");
                    cropy = cropy.Replace(".", ",");

                    Decimal Convcropweight = Decimal.Parse(cropweight);
                    Decimal Convcropcropwidth = Decimal.Parse(cropwidth);
                    Decimal Convcropx = Decimal.Parse(cropx);
                    Decimal Convcropy = Decimal.Parse(cropy);

                    Rectangle cropRect = new Rectangle(Decimal.ToInt32(Convcropx), Decimal.ToInt32(Convcropy), Decimal.ToInt32(Convcropcropwidth), Decimal.ToInt32(Convcropweight));

                    Bitmap src = Image.FromStream(file.InputStream) as Bitmap;

                    Bitmap target = new Bitmap(cropRect.Width, cropRect.Height);

                    using (Graphics g = Graphics.FromImage(target))
                    {
                        g.DrawImage(src, new Rectangle(0, 0, target.Width, target.Height),
                            cropRect,
                            GraphicsUnit.Pixel);
                    }

                    target = new Bitmap(target, new Size(125, 125));

                    target.Save(archivo);

                    model.Imagen = "/PerfilImg/" + model.Telefono + "-" + model.NombreApellidos + "." + file.ContentType.Remove(0, 6);
                    //model.Imagen = "/PerfilImg/" + model.Telefono + "-" + model.NombreApellidos + "." + file.FileName;
                }
                else
                {
                    model.Imagen = "/PerfilImg/SinImagen.jpg";
                }

                if (model.IdOcupacionCultural == 0)
                {

ddcCajamarca.Web/Views/Directorio/Eliminar.cshtml
<script type="text/javascript">
    var msg = '@ViewBag.MSG';
</script>

ddcCajamarca.Web/Views/Directorio/EliminarExtra.cshtml
<script type="text/javascript">
    var msg = '@ViewBag.MSG';
</script>

ddcCajamarca.Web/Views/Directorio/GuardarExtra.cshtml
<script type="text/javascript">
    var msg = '@ViewBag.MSG';
</script>

ddcCajamarca.Web/Views/Directorio/_GuardarExtra.cshtml
<script type="text/javascript">
    var msg = '@ViewBag.MSG';
</script>

ddcCajamarca.Web/Views/Directorio/_GuardarOcupacionPersona.cshtml
@{
    IEnumerable<SelectListItem> Ocupacion = new SelectList(@ViewBag.Ocupacion, "Id", "Nombre");
}

@Html.DropDownList("IdOcupacionCultural", Ocupacion, "-- Seleccionar --", new { @class = "form-control" })
<span onclick="abrirmodalOcupacion()" class="input-group-addon btn btn-primary btn-xs"><a href="#"><i style="color:darkslategrey" class="fa fa-plus"></i></a></span>

ddcCajamarca.Web/Views/Directorio/_GuardarOrganizacionPersona.cshtml
@{
    IEnumerable<SelectListItem> Organizacion = new SelectList(@ViewBag.Organizacion, "Id", "Nombre");
}

@Html.DropDownList("IdOrganizacion", Organizacion, "-- Seleccionar --", new { @class = "form-control" })
<span onclick="abrirmodalOrganizacion()" class="input-group-addon btn btn-primary btn-xs"><a href="#"><i style="color:darkslategrey" class="fa fa-plus"></i></a></span>

ddcCajamarca.Web/Views/Directorio/_GuardarProfesionPersona.cshtml
@{
    IEnumerable<SelectListItem> Profesion = new SelectList(@ViewBag.Profesion, "Id", "Nombre");
}

@Html.DropDownList("IdProfesion", Profesion, "-- Seleccionar --", new { @class = "form-control" })
<span onclick="abrirmodalProfesion()" class="input-group-addon btn btn-primary btn-xs"><a href="#"><i style="color:darkslategrey" class="fa fa-plus"></i></a></span>

ddcCajamarca.Web/Views/Directorio/_Listar.cshtml
<div class="col-sm-12 text-right">
    <p>@ViewBag.Coincidencias resultados encontrados.</p>
</div>
<table class="table table-stripped" data-show-toggle="false" data-filtering="true" data-page-size="15">
    <thead>
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th data-hide="all">Nombre Artistico</th>
            <th data-hide="phone,tablet">Ocupación Cultural</th>
            <th data-hide="phone">Dirección</th>
            <th data-hide="phone">Telefono</th>
            <th data-hide="all">Fecha Nacimiento</th>
            <th data-hide="all">Email</th>
            <th data-hide="all">RedesSociales</th>
            <th data-hide="all">Profesión</th>
            <th data-hide="all">Organización</th>
            <th data-hide="phone,tablet">Fecha Modificada</th>
            <th data-toggle="true" data-breakpoints="xs" class="text-center">Acciones</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
            {
            <tr>
                <td class="client-avatar"><img alt="image" src="@item.Imagen.ToString()"> </td>
                <td>@item.NombreApellidos</td>
                <td>@item.NombreArtistico</td>
                <td>@item.OcupacionCultural.Nombre</td>
                <td>@item.Direccion</td>
                <td>@item.Telefono</td>
                <td>@item.FechaNacimiento</td>
                <td>@item.Email</td>
                <td>@item.RedesSociales</td>
                <td>@item.Profesion.Nombre</td>
                <td>@item.Organizacion.Nombre</td>
                <td>@item.FechaRegistroMostrar</td>
                <td class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-warning btn-xs" href="@Url.Action("Editar", "Directorio",new {idper = @item.Id})">Modificar</a>
                        <a href="#" class="btn btn-danger btn-xs" onclick="abrirmodalelim(@item.Id)">Eliminar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

ddcCajamarca.Web/Views/Directorio/_ListarExtras.cshtml
<div class="col-sm-12 text-right">
    <p>@ViewBag.Coincidencias resultados encontrados.</p>
</div>
<table class="table table-stripped" data-show-toggle="false" data-filtering="true" data-page-size="10">
    <thead>
        @{
            if (ViewBag.lista == "L3")
            {
                <tr>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>FechaRegistro</th>
                    <th class="text-center">Acciones</th>
                </tr>
            }
            else
            {
                <tr>
                    <th>Nombre</th>
                    <th>FechaRegistro</th>
                    <th class="text-center">Acciones</th>
                </tr>
            }

        }
        
    </thead>
    <tbody>
        @{
            if (ViewBag.lista == "L3")
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Direccion</td>
                        <td>@item.FechaRegistroMostrar</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="#" class="btn btn-warning btn-xs" onclick="abrirmodalmod(@item.Id)">Modificar</a>
                                <a href="#" class="btn btn-danger btn-xs" onclick="abrirmodalelim(@item.Id)">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.FechaRegistroMostrar</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="#" class="btn btn-warning btn-xs" onclick="abrirmodalmod(@item.Id)">Modificar</a>
                                <a href="#" class="btn btn-danger btn-xs" onclick="abrirmodalelim(@item.Id)">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        }
        
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>

ddcCajamarca.Web/Views/Directorio/_ModificarExtra.cshtml
<script type="text/javascript">
    var msg = '@ViewBag.msg';
</script>

ddcCajamarca.Web/Views/Directorio/_OBtenerExtraPorId.cshtml
<div class="form-group col-lg-12">
    <label>Fecha de Edición</label>
    <input name="FechaRegistro" type='text' class="form-control" readonly value="@ViewBag.FechaHoy" />
</div>
<div class="form-group col-lg-12">
    <label>Nombre*</label>
    <input name="txtNombreMod" value="@Model.Nombre" id="txtNombreMod" placeholder="INGRESE NOMBRE" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required autocomplete="off">
</div>
@{
    if (ViewBag.ModTipo == "M3")
    {
        <div class="form-group col-lg-12">
            <label>Direccion*</label>
            <input name="txtDireccionOrganizacionMod" id="txtDireccionOrganizacionMod" value="@Model.Direccion" placeholder="INGRESE DIRECCION" class="form-control" data-provide="typeahead" style="text-transform:uppercase;" required autocomplete="off">
        </div>
    }
}
<input id="txtIdMod" hidden value="@Model.Id" />
<p>*El campo nombre es obligatorio</p>